### ISSUE TITLE
Fail after Toggle(1)

### ISSUE THREAD

**Issue by Defragster** [Defragster/tti2c#1]
These are rare on k66 - much more reg on 1062
T:\tCode\i2c\T4_i2c_tb_v5\T4_i2c_tb_v5.ino Feb  3 2020 22:40:39

I2C Scanner
Scanning(Wire)...
Device found at address 0x09  (unknown chip)
Device found at address 0x29  (TSL2561,VL6180,TSL2561,TSL2591,BNO055,CAP1188)
Device found at address 0x4B  (ADS1115,TMP102,BNO080,Qwiic Keypad)
Device found at address 0x50  (EEPROM,FRAM)
Device found at address 0x62  (LidarLite,MCP4725,AtlasEzoORP,Qwiic Button)
Device found at address 0x68  (DS1307,DS3231,MPU6050,MPU9050,MPU9250,ITG3200,ITG3701,LSM9DS0,L3G4200D,Qwiic Button)
Device found at address 0x7C  (FRAM_ID)
done

Scanning(Wire1)...
Device found at address 0x3C  (SSD1306,DigisparkOLED)
done

Scanning(Wire2)...
No I2C devices found

TC #1	TC SDA read: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
Starting MB85...

Hello

9250 Initialized
055 Initialized
Current Temperature: 28 C

Calibration status values: 0=uncalibrated, 3=fully calibrated
080 Init	BNO080 not detected at default I2C address. Check your jumpers and the hookup guide. TOGGLE...
... TOGGLE
TC #1	TC SDA read: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
080 Init	BNO080 not detected at default I2C address. Check your jumpers and the hookup guide. Freezing...
... **FAIL**Scanning(Wire)...
Device found at address 0x29  (TSL2561,VL6180,TSL2561,TSL2591,BNO055,CAP1188)
Unknown error at address 0x4B	**MCR:1 MSR:b01, MIER:0 MDER:0 MCFGR0:0 MDMR:0** MCCR0:1928373b
Device found at address 0x50  (EEPROM,FRAM)
Device found at address 0x62  (LidarLite,MCP4725,AtlasEzoORP,Qwiic Button)
Device found at address 0x68  (DS1307,DS3231,MPU6050,MPU9050,MPU9250,ITG3200,ITG3701,LSM9DS0,L3G4200D,Qwiic Button)
Device found at address 0x7C  (FRAM_ID)
done

**Comment by Defragster** [comment]
Next TyComm Reset Recovered - reset had to Recover again - twice then it worked:


Calibration status values: 0=uncalibrated, 3=fully calibrated
080 Init	BNO080 not detected at default I2C address. Check your jumpers and the hookup guide. TOGGLE...
... TOGGLE
TC #1	TC SDA read: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
080 Init
Recovered

Recovered << ============================================================= 

Recovered << =============================================================

**Comment by Defragster** [comment]
1062: TyComm power on Good - then R==Resets (Fail or Recover on BNO080)::
R:Fail, R:Rec, R:Rec, R:Fail, R:Rec, R:Fail, R:Fail, R:Fail, R:Good, R:Good, R:Rec, R:Good, R:Good, R:Fail, R:Good, R:Fail, R:Fail, R:Rec, R:Fail, R:Rec, R: Good
#6: Good. #9: Fail. #6 Recover :: 21 runs/restarts
*: No LL3 NAck'd here when it ran.

1062: TyComm Upload:
U:Fail, U:Good, U:Rec, U:Good, U:Fail, U:Rec, U:Rec, U:Rec, U:Good, U:Fail, U:Good, U:Good, U:Good, U:Fail, U:Fail, U:Fail
#5: Fail, #6:Good, #4:Recover :: 15 Ctrl+U Uploads.

**Comment by mjs513** [comment]
Tim = see issue #3

**Comment by Defragster** [comment]
Seems to be cleared up with proper - uninterrupted BN)080 .begin startup
