### ISSUE TITLE
LL3 aNak streams

### ISSUE THREAD

**Issue by Defragster** [Defragster/tti2c#2]
with test board I've seen limited (from the 100 read groups?) and perhaps unlimted:
    Serial.println("> Nack");

3 here: T:\tCode\libraries\LIDARLite\src\LIDARLite.cpp:
2 here: T:\tCode\libraries\LIDARLite\src\LIDARLite_v3HP.cpp:

Might be good to identify these for a pattern and better handling?

both k66 and 1062 - but rare

**Comment by mjs513** [comment]
Note:  For me I really didn't see this issue with LL3 prior to attaching the additional 3 i2c devices: Button, keypad and SHT31 temp sensor and blinking the T4 and T3.2.  May be a power issue.  See the [Troubleshooting](https://learn.sparkfun.com/tutorials/lidar-lite-v3-hookup-guide) section on Sparkfun's LL3 hookup guide

**Comment by mjs513** [comment]
Since I made the change to make sure the clocks are at 400khz I haven't seen any nacks - I lied saw it once on 1 initial load.
