### ISSUE TITLE
Can't email?

### ISSUE THREAD

**Issue by Defragster** [Defragster/tti2c#4]
Tried this a third time and was rejected - follow up to prior:
… ODD … TWICE … Mail Rejected again – Both servers ‘protected as SPAM’ … Changed Subject after first … restarted MAIL again …
… Sent: Wednesday, February 5, 2020 12:49:30 AM
 
The EMAIL Retry didn’t give Rejected message … never saw that before.  I use “Mail for Windows 10” on this Hotmail account – closed and restarted Mail before resend.
 
I didn’t look at any features/options on button/keypad – just watched it work and cleaned up some output, hid W_DOG code if not T4’s 1062.  Updated VK_Slave on github. Also didn’t try FASTER i2c yet.
 
Saw NO COMM issues with BNO080 – not sure what changed – except valid .begin?  After github update I even took it out of setup() with Toggle(0) and seems okay after a few runs.
 
Of course another Reset after I say that I get INFINITE and fast “> nAck” from :: T:\tCode\libraries\LIDARLite\src\LIDARLite.cpp: > 291:       Serial.println("> nAck");
Will upload two LL3 files that print like this {I switched LL3 to Wire1 to cause this) showing which of 2 files and the line# and Error value: 294 in LL 2 == Nack with:
      Serial.print(__LINE__);
      Serial.print(" in 3HP ");
      Serial.print(nackCatcher);
     Serial.print(" == Nack\n");
 
I have another SSD1306 on my desk – could wire that up Qwiic – or plug it into FRDM i2c Wire socket for alternate output on another Wire#.
 
Not sure what T_3.2 slave code should do – it prints garbage string so it is getting something?  Shading with finger I see it is doing LED blink too fast/dim. Changed and uploaded as an Example.  Now LED Toggles and HEX prints the initial rcv chars.

**Comment by mjs513** [comment]
Morning Tim
From these examples:
https://github.com/madsci1016/Arduino-EasyTransfer/tree/master/EasyTransferI2C/examples,
the RX sketch should go on the T3.2.  What you should see happening is that
LED on the T3.2 is in sync with the LED blinking on the T4.

Only 2 things changed in the Slave sketch
1.  the valid begin for the BNO080
2.  WDT start moved to end of Setup.  Thought it might the WDT might be
timing out before it had a chance to finish running the recover code.

Are you using the change Wire library?

Going to download your latest changes and give it a go.
